version: "3.7"
services:
    backend:
        image: nodecenter/mgr
        ports:
            - "5000:5000"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
    frontend:
        image: nodecenter/ux
        ports:
            - "8080:80"
